# Generated by Django 4.2.6 on 2024-01-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raeume',
            fields=[
                ('raumNR', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bestuhlung', models.IntegerField()),
                ('ausstattung', models.CharField(choices=[('hoch', 'hoch'), ('mittel', 'mittel'), ('niedrig', 'niedrig')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MyBookings',
            fields=[
                ('buchungsNR', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('raumNR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.raeume')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
